// <auto-generated />
using System;
using Inventarios_BE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventarios_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Inventarios_BE.Entidades.Producto", b =>
                {
                    b.Property<long>("PRO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PRO_ID"), 1L, 1);

                    b.Property<bool>("PRO_ANTIVIRUS")
                        .HasColumnType("bit");

                    b.Property<string>("PRO_ANYDESK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_ASIGNADO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_COD_ACTIVO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_CON_ANYDESK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_CPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_DIRECCION_IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PRO_FECHA_INGRESO")
                        .HasColumnType("datetime2");

                    b.Property<string>("PRO_FILESERVER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_GEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_MARCA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PRO_MODELO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_NOMBRE_PRODUCTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_NUC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_OFFICE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_SERIAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_SO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_USER_WIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_USO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO_WIN_CON")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRO_ID");

                    b.ToTable("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
